version: "3.8"

services:
  db:
    image: postgres:16
    container_name: crm_hrm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: crm_hrm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - crm_hrm_pgdata:/var/lib/postgresql/data

volumes:
  crm_hrm_pgdata:
