// Field types: text, textarea, number, date, time, select, select-async, checkbox, email
// select-async fields fetch options from `optionsEndpoint` (relative to /api) at form-open time.

export const CRM_MODULES = [
  {
    key: 'leads', num: 1, label: 'Leads', path: '/crm/leads', api: '/crm/leads',
    description: 'Capture and qualify inbound and outbound leads.',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'company_name', label: 'Company' },
      { key: 'source_name', label: 'Source' },
      { key: 'status', label: 'Status', type: 'pill' },
      { key: 'score', label: 'Score' },
      { key: 'estimated_value', label: 'Est. Value', type: 'currency' },
      { key: 'owner_name', label: 'Owner' },
    ],
    fields: [
      { key: 'name', label: 'Lead Name', type: 'text', required: true },
      { key: 'company_name', label: 'Company Name', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'source_id', label: 'Source', type: 'select-async', optionsEndpoint: '/meta/lead-sources' },
      { key: 'status', label: 'Status', type: 'select', options: ['new', 'contacted', 'qualified', 'unqualified', 'converted'] },
      { key: 'score', label: 'Score (0-100)', type: 'number' },
      { key: 'estimated_value', label: 'Estimated Value', type: 'number' },
      { key: 'owner_id', label: 'Owner', type: 'select-async', optionsEndpoint: '/users' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    rowActions: [
      { label: 'Convert', variant: 'btn-secondary', hideIf: (r) => r.status === 'converted', action: (row, api) => api.post(`/crm/leads/${row.id}/convert`) },
    ],
  },
  {
    key: 'companies', num: 2, label: 'Companies', path: '/crm/companies', api: '/crm/companies',
    description: 'The organizations you sell to and support.',
    columns: [
      { key: 'name', label: 'Company' },
      { key: 'industry', label: 'Industry' },
      { key: 'city', label: 'City' },
      { key: 'phone', label: 'Phone' },
      { key: 'annual_revenue', label: 'Revenue', type: 'currency' },
      { key: 'owner_name', label: 'Owner' },
    ],
    fields: [
      { key: 'name', label: 'Company Name', type: 'text', required: true },
      { key: 'industry', label: 'Industry', type: 'text' },
      { key: 'website', label: 'Website', type: 'text' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'city', label: 'City', type: 'text' },
      { key: 'state', label: 'State', type: 'text' },
      { key: 'country', label: 'Country', type: 'text' },
      { key: 'annual_revenue', label: 'Annual Revenue', type: 'number' },
      { key: 'employee_count', label: 'Employee Count', type: 'number' },
      { key: 'owner_id', label: 'Owner', type: 'select-async', optionsEndpoint: '/users' },
      { key: 'billing_address', label: 'Billing Address', type: 'textarea' },
      { key: 'shipping_address', label: 'Shipping Address', type: 'textarea' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'contacts', num: 3, label: 'Contacts', path: '/crm/contacts', api: '/crm/contacts',
    description: 'People at your customer and prospect companies.',
    columns: [
      { key: 'first_name', label: 'First Name' },
      { key: 'last_name', label: 'Last Name' },
      { key: 'company_name', label: 'Company' },
      { key: 'email', label: 'Email' },
      { key: 'phone', label: 'Phone' },
      { key: 'designation', label: 'Designation' },
    ],
    fields: [
      { key: 'first_name', label: 'First Name', type: 'text', required: true },
      { key: 'last_name', label: 'Last Name', type: 'text' },
      { key: 'company_id', label: 'Company', type: 'select-async', optionsEndpoint: '/crm/companies' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'designation', label: 'Designation', type: 'text' },
      { key: 'department', label: 'Department', type: 'text' },
      { key: 'is_primary', label: 'Primary contact for company', type: 'checkbox' },
      { key: 'owner_id', label: 'Owner', type: 'select-async', optionsEndpoint: '/users' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'activities', num: 6, label: 'Activities & Follow-ups', path: '/crm/activities', api: '/crm/activities',
    description: 'Calls, meetings, tasks and follow-ups across CRM records.',
    columns: [
      { key: 'subject', label: 'Subject' },
      { key: 'type', label: 'Type', type: 'pill' },
      { key: 'due_date', label: 'Due', type: 'date' },
      { key: 'priority', label: 'Priority', type: 'pill' },
      { key: 'status', label: 'Status', type: 'pill' },
      { key: 'assigned_to_name', label: 'Assigned To' },
    ],
    fields: [
      { key: 'subject', label: 'Subject', type: 'text', required: true },
      { key: 'type', label: 'Type', type: 'select', options: ['call', 'meeting', 'task', 'email', 'follow_up'] },
      { key: 'related_to_type', label: 'Related To (type)', type: 'select', options: ['lead', 'deal', 'contact', 'company'] },
      { key: 'related_to_id', label: 'Related Record ID', type: 'number' },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high'] },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'completed', 'cancelled'] },
      { key: 'assigned_to', label: 'Assigned To', type: 'select-async', optionsEndpoint: '/users' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'products', num: 9, label: 'Products & Services', path: '/crm/products', api: '/crm/products',
    description: 'The catalog used when building quotations and orders.',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'sku', label: 'SKU', type: 'mono' },
      { key: 'type', label: 'Type', type: 'pill' },
      { key: 'unit_price', label: 'Unit Price', type: 'currency' },
      { key: 'tax_percent', label: 'Tax %' },
      { key: 'is_active', label: 'Active', type: 'boolean' },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'sku', label: 'SKU', type: 'text' },
      { key: 'type', label: 'Type', type: 'select', options: ['product', 'service'] },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'unit_price', label: 'Unit Price', type: 'number', required: true },
      { key: 'tax_percent', label: 'Tax %', type: 'number' },
      { key: 'is_active', label: 'Active', type: 'checkbox' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    key: 'communications', num: 10, label: 'Customer Communication', path: '/crm/communications', api: '/crm/communications',
    description: 'A log of every email, call and message with customers.',
    columns: [
      { key: 'type', label: 'Type', type: 'pill' },
      { key: 'direction', label: 'Direction' },
      { key: 'subject', label: 'Subject' },
      { key: 'contact_first_name', label: 'Contact' },
      { key: 'logged_by_name', label: 'Logged By' },
      { key: 'occurred_at', label: 'When', type: 'datetime' },
    ],
    fields: [
      { key: 'type', label: 'Type', type: 'select', options: ['email', 'call', 'sms', 'whatsapp', 'meeting_note'], required: true },
      { key: 'direction', label: 'Direction', type: 'select', options: ['inbound', 'outbound'] },
      { key: 'subject', label: 'Subject', type: 'text' },
      { key: 'body', label: 'Body / Notes', type: 'textarea' },
      { key: 'contact_id', label: 'Contact', type: 'select-async', optionsEndpoint: '/crm/contacts' },
      { key: 'related_to_type', label: 'Related To (type)', type: 'select', options: ['lead', 'deal', 'company'] },
      { key: 'related_to_id', label: 'Related Record ID', type: 'number' },
      { key: 'logged_by', label: 'Logged By', type: 'select-async', optionsEndpoint: '/users' },
    ],
  },
];

export const CRM_CUSTOM_PAGES = [
  { key: 'crm-dashboard', num: 12, label: 'CRM Dashboard', path: '/crm/dashboard' },
  { key: 'deals', num: 4, label: 'Deals (Pipeline)', path: '/crm/deals-pipeline', pipelineLabel: 'Sales Pipeline (5)' },
  { key: 'quotations', num: 7, label: 'Quotations', path: '/crm/quotations-page' },
  { key: 'sales-orders', num: 8, label: 'Sales Orders', path: '/crm/sales-orders-page' },
  { key: 'tickets', num: 11, label: 'Support Tickets', path: '/crm/tickets-page' },
  { key: 'documents', num: 13, label: 'Document Upload', path: '/crm/documents-page' },
];
