export const HRM_MODULES = [
  {
    key: 'employees', num: 1, label: 'Employees', path: '/hrm/employees', api: '/hrm/employees',
    description: 'The single source of truth for everyone in the organization.',
    columns: [
      { key: 'employee_code', label: 'Code', type: 'mono' },
      { key: 'first_name', label: 'First Name' },
      { key: 'last_name', label: 'Last Name' },
      { key: 'department_name', label: 'Department' },
      { key: 'designation_title', label: 'Designation' },
      { key: 'status', label: 'Status', type: 'pill' },
      { key: 'date_of_joining', label: 'Joined', type: 'date' },
    ],
    fields: [
      { key: 'employee_code', label: 'Employee Code', type: 'text', required: true },
      { key: 'first_name', label: 'First Name', type: 'text', required: true },
      { key: 'last_name', label: 'Last Name', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'gender', label: 'Gender', type: 'select', options: ['male', 'female', 'other'] },
      { key: 'date_of_birth', label: 'Date of Birth', type: 'date' },
      { key: 'date_of_joining', label: 'Date of Joining', type: 'date' },
      { key: 'department_id', label: 'Department', type: 'select-async', optionsEndpoint: '/meta/departments' },
      { key: 'designation_id', label: 'Designation', type: 'select-async', optionsEndpoint: '/meta/designations', optionsLabel: 'title' },
      { key: 'manager_id', label: 'Manager', type: 'select-async', optionsEndpoint: '/hrm/employees', optionsLabel: 'first_name' },
      { key: 'employment_type', label: 'Employment Type', type: 'select', options: ['full_time', 'part_time', 'contract', 'intern'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'on_leave', 'exited'] },
      { key: 'ctc_annual', label: 'Annual CTC', type: 'number' },
      { key: 'bank_account_no', label: 'Bank Account No.', type: 'text' },
      { key: 'address', label: 'Address', type: 'textarea' },
      { key: 'emergency_contact_name', label: 'Emergency Contact Name', type: 'text' },
      { key: 'emergency_contact_phone', label: 'Emergency Contact Phone', type: 'text' },
    ],
  },
  {
    key: 'job-openings', num: 3, label: 'Job Openings', path: '/hrm/job-openings', api: '/hrm/recruitment/job-openings',
    description: 'Open requisitions across the organization.',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'department_name', label: 'Department' },
      { key: 'employment_type', label: 'Type' },
      { key: 'openings_count', label: 'Openings' },
      { key: 'status', label: 'Status', type: 'pill' },
      { key: 'posted_date', label: 'Posted', type: 'date' },
    ],
    fields: [
      { key: 'title', label: 'Job Title', type: 'text', required: true },
      { key: 'department_id', label: 'Department', type: 'select-async', optionsEndpoint: '/meta/departments' },
      { key: 'employment_type', label: 'Employment Type', type: 'select', options: ['full_time', 'part_time', 'contract', 'intern'] },
      { key: 'openings_count', label: 'Number of Openings', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'on_hold', 'closed'] },
      { key: 'posted_date', label: 'Posted Date', type: 'date' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    key: 'candidates', num: 3, label: 'Candidates', path: '/hrm/candidates', api: '/hrm/recruitment/candidates',
    description: 'Applicants moving through your hiring pipeline.',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'job_title', label: 'Applying For' },
      { key: 'email', label: 'Email' },
      { key: 'stage', label: 'Stage', type: 'pill' },
      { key: 'source', label: 'Source' },
    ],
    fields: [
      { key: 'name', label: 'Candidate Name', type: 'text', required: true },
      { key: 'job_opening_id', label: 'Job Opening', type: 'select-async', optionsEndpoint: '/hrm/recruitment/job-openings', optionsLabel: 'title' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'stage', label: 'Stage', type: 'select', options: ['applied', 'screening', 'interview', 'offer', 'hired', 'rejected'] },
      { key: 'source', label: 'Source', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'onboarding', num: 4, label: 'Onboarding', path: '/hrm/onboarding', api: '/hrm/onboarding',
    description: 'Track tasks for every new hire\u2019s first weeks.',
    columns: [
      { key: 'task_name', label: 'Task' },
      { key: 'first_name', label: 'Employee' },
      { key: 'category', label: 'Category' },
      { key: 'status', label: 'Status', type: 'pill' },
      { key: 'due_date', label: 'Due', type: 'date' },
    ],
    fields: [
      { key: 'employee_id', label: 'Employee', type: 'select-async', optionsEndpoint: '/hrm/employees', optionsLabel: 'first_name', required: true },
      { key: 'task_name', label: 'Task', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['documentation', 'IT setup', 'training', 'HR'] },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'done'] },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'assigned_to', label: 'Assigned To', type: 'select-async', optionsEndpoint: '/users' },
    ],
  },
  {
    key: 'attendance', num: 5, label: 'Attendance', path: '/hrm/attendance', api: '/hrm/attendance',
    description: 'Daily check-in / check-out records.',
    columns: [
      { key: 'first_name', label: 'Employee' },
      { key: 'employee_code', label: 'Code', type: 'mono' },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'check_in', label: 'Check In' },
      { key: 'check_out', label: 'Check Out' },
      { key: 'status', label: 'Status', type: 'pill' },
    ],
    fields: [
      { key: 'employee_id', label: 'Employee', type: 'select-async', optionsEndpoint: '/hrm/employees', optionsLabel: 'first_name', required: true },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'check_in', label: 'Check In', type: 'time' },
      { key: 'check_out', label: 'Check Out', type: 'time' },
      { key: 'status', label: 'Status', type: 'select', options: ['present', 'absent', 'half_day', 'wfh', 'on_leave'] },
      { key: 'work_hours', label: 'Work Hours', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'leave-requests', num: 6, label: 'Leave Requests', path: '/hrm/leave', api: '/hrm/leave',
    description: 'Employee time-off requests and approvals.',
    columns: [
      { key: 'first_name', label: 'Employee' },
      { key: 'leave_type_name', label: 'Leave Type' },
      { key: 'start_date', label: 'From', type: 'date' },
      { key: 'end_date', label: 'To', type: 'date' },
      { key: 'total_days', label: 'Days' },
      { key: 'status', label: 'Status', type: 'pill' },
    ],
    fields: [
      { key: 'employee_id', label: 'Employee', type: 'select-async', optionsEndpoint: '/hrm/employees', optionsLabel: 'first_name', required: true },
      { key: 'leave_type_id', label: 'Leave Type', type: 'select-async', optionsEndpoint: '/meta/leave-types', required: true },
      { key: 'start_date', label: 'Start Date', type: 'date', required: true },
      { key: 'end_date', label: 'End Date', type: 'date', required: true },
      { key: 'total_days', label: 'Total Days', type: 'number' },
      { key: 'reason', label: 'Reason', type: 'textarea' },
    ],
    rowActions: [
      { label: 'Approve', variant: 'btn-secondary', hideIf: (r) => r.status !== 'pending', action: (row, api) => api.post(`/hrm/leave/${row.id}/approve`) },
      { label: 'Reject', variant: 'btn-danger', hideIf: (r) => r.status !== 'pending', action: (row, api) => api.post(`/hrm/leave/${row.id}/reject`) },
    ],
  },
  {
    key: 'loans', num: 16, label: 'Loans & Advances', path: '/hrm/loans', api: '/hrm/loans',
    description: 'Employee salary advance / personal loan requests and repayment tracking.',
    columns: [
      { key: 'first_name', label: 'Employee' },
      { key: 'loan_type', label: 'Type', type: 'pill' },
      { key: 'amount', label: 'Amount', type: 'currency' },
      { key: 'monthly_deduction', label: 'Monthly Deduction', type: 'currency' },
      { key: 'requested_date', label: 'Requested', type: 'date' },
      { key: 'status', label: 'Status', type: 'pill' },
    ],
    fields: [
      { key: 'employee_id', label: 'Employee', type: 'select-async', optionsEndpoint: '/hrm/employees', optionsLabel: 'first_name', required: true },
      { key: 'loan_type', label: 'Loan Type', type: 'select', options: ['salary_advance', 'personal_loan'], required: true },
      { key: 'amount', label: 'Amount', type: 'number', required: true },
      { key: 'monthly_deduction', label: 'Monthly Deduction', type: 'number' },
      { key: 'requested_date', label: 'Requested Date', type: 'date' },
      { key: 'reason', label: 'Reason', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'approved', 'rejected', 'disbursed', 'closed'] },
      { key: 'disbursed_date', label: 'Disbursed Date', type: 'date' },
      { key: 'outstanding_balance', label: 'Outstanding Balance', type: 'number' },
    ],
    rowActions: [
      { label: 'Approve', variant: 'btn-secondary', hideIf: (r) => r.status !== 'pending', action: (row, api) => api.post(`/hrm/loans/${row.id}/approve`) },
      { label: 'Reject', variant: 'btn-danger', hideIf: (r) => r.status !== 'pending', action: (row, api) => api.post(`/hrm/loans/${row.id}/reject`) },
    ],
  },
  {
    key: 'holidays', num: 7, label: 'Holidays', path: '/hrm/holidays', api: '/hrm/holidays',
    description: 'The official company holiday calendar.',
    columns: [
      { key: 'name', label: 'Holiday' },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'type', label: 'Type', type: 'pill' },
    ],
    fields: [
      { key: 'name', label: 'Holiday Name', type: 'text', required: true },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'type', label: 'Type', type: 'select', options: ['public', 'optional'] },
    ],
  },
  {
    key: 'expenses', num: 9, label: 'Expenses', path: '/hrm/expenses', api: '/hrm/expenses',
    description: 'Employee expense claims and reimbursements.',
    columns: [
      { key: 'first_name', label: 'Employee' },
      { key: 'category', label: 'Category' },
      { key: 'amount', label: 'Amount', type: 'currency' },
      { key: 'expense_date', label: 'Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'pill' },
    ],
    fields: [
      { key: 'employee_id', label: 'Employee', type: 'select-async', optionsEndpoint: '/hrm/employees', optionsLabel: 'first_name', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['travel', 'food', 'accommodation', 'misc'] },
      { key: 'amount', label: 'Amount', type: 'number', required: true },
      { key: 'expense_date', label: 'Expense Date', type: 'date', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
    rowActions: [
      { label: 'Approve', variant: 'btn-secondary', hideIf: (r) => r.status !== 'pending', action: (row, api) => api.post(`/hrm/expenses/${row.id}/approve`) },
      { label: 'Reject', variant: 'btn-danger', hideIf: (r) => r.status !== 'pending', action: (row, api) => api.post(`/hrm/expenses/${row.id}/reject`) },
    ],
  },
  {
    key: 'performance-reviews', num: 10, label: 'Performance Reviews', path: '/hrm/performance-reviews', api: '/hrm/performance/reviews',
    description: 'Structured review cycles for every employee.',
    columns: [
      { key: 'first_name', label: 'Employee' },
      { key: 'review_period', label: 'Period' },
      { key: 'rating', label: 'Rating' },
      { key: 'reviewer_name', label: 'Reviewer' },
      { key: 'status', label: 'Status', type: 'pill' },
    ],
    fields: [
      { key: 'employee_id', label: 'Employee', type: 'select-async', optionsEndpoint: '/hrm/employees', optionsLabel: 'first_name', required: true },
      { key: 'reviewer_id', label: 'Reviewer', type: 'select-async', optionsEndpoint: '/users' },
      { key: 'review_period', label: 'Review Period', type: 'text', placeholder: 'e.g. Q1 2026' },
      { key: 'rating', label: 'Rating (1-5)', type: 'number' },
      { key: 'strengths', label: 'Strengths', type: 'textarea' },
      { key: 'improvements', label: 'Areas to Improve', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'submitted', 'acknowledged'] },
    ],
  },
  {
    key: 'goals', num: 10, label: 'Goals', path: '/hrm/goals', api: '/hrm/performance/goals',
    description: 'Individual goals tracked alongside performance reviews.',
    columns: [
      { key: 'title', label: 'Goal' },
      { key: 'first_name', label: 'Employee' },
      { key: 'target_date', label: 'Target', type: 'date' },
      { key: 'progress', label: 'Progress %' },
      { key: 'status', label: 'Status', type: 'pill' },
    ],
    fields: [
      { key: 'employee_id', label: 'Employee', type: 'select-async', optionsEndpoint: '/hrm/employees', optionsLabel: 'first_name', required: true },
      { key: 'title', label: 'Goal Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'target_date', label: 'Target Date', type: 'date' },
      { key: 'progress', label: 'Progress (0-100)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['in_progress', 'completed', 'missed'] },
    ],
  },
  {
    key: 'training-programs', num: 11, label: 'Training Programs', path: '/hrm/training-programs', api: '/hrm/training/programs',
    description: 'Scheduled training and development programs.',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'trainer', label: 'Trainer' },
      { key: 'start_date', label: 'Start', type: 'date' },
      { key: 'end_date', label: 'End', type: 'date' },
      { key: 'status', label: 'Status', type: 'pill' },
    ],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'trainer', label: 'Trainer', type: 'text' },
      { key: 'start_date', label: 'Start Date', type: 'date' },
      { key: 'end_date', label: 'End Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['scheduled', 'ongoing', 'completed', 'cancelled'] },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    key: 'training-enrollments', num: 11, label: 'Training Enrollments', path: '/hrm/training-enrollments', api: '/hrm/training/enrollments',
    description: 'Who is enrolled in which training program.',
    columns: [
      { key: 'first_name', label: 'Employee' },
      { key: 'training_title', label: 'Training' },
      { key: 'status', label: 'Status', type: 'pill' },
      { key: 'score', label: 'Score' },
    ],
    fields: [
      { key: 'training_id', label: 'Training Program', type: 'select-async', optionsEndpoint: '/hrm/training/programs', optionsLabel: 'title', required: true },
      { key: 'employee_id', label: 'Employee', type: 'select-async', optionsEndpoint: '/hrm/employees', optionsLabel: 'first_name', required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['enrolled', 'completed', 'dropped'] },
      { key: 'score', label: 'Score', type: 'number' },
    ],
  },
  {
    key: 'assets', num: 13, label: 'Assets', path: '/hrm/assets', api: '/hrm/assets',
    description: 'Company equipment and who it\u2019s assigned to.',
    columns: [
      { key: 'asset_tag', label: 'Tag', type: 'mono' },
      { key: 'name', label: 'Asset' },
      { key: 'category', label: 'Category' },
      { key: 'status', label: 'Status', type: 'pill' },
      { key: 'first_name', label: 'Assigned To' },
    ],
    fields: [
      { key: 'asset_tag', label: 'Asset Tag', type: 'text', required: true },
      { key: 'name', label: 'Asset Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['laptop', 'phone', 'furniture', 'other'] },
      { key: 'serial_number', label: 'Serial Number', type: 'text' },
      { key: 'purchase_date', label: 'Purchase Date', type: 'date' },
      { key: 'purchase_cost', label: 'Purchase Cost', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['available', 'assigned', 'maintenance', 'retired'] },
    ],
  },
  {
    key: 'offboarding', num: 14, label: 'Exit / Offboarding', path: '/hrm/offboarding', api: '/hrm/offboarding',
    description: 'Manage resignations, clearances and exit interviews.',
    columns: [
      { key: 'first_name', label: 'Employee' },
      { key: 'resignation_date', label: 'Resigned', type: 'date' },
      { key: 'last_working_day', label: 'Last Day', type: 'date' },
      { key: 'status', label: 'Status', type: 'pill' },
    ],
    fields: [
      { key: 'employee_id', label: 'Employee', type: 'select-async', optionsEndpoint: '/hrm/employees', optionsLabel: 'first_name', required: true },
      { key: 'resignation_date', label: 'Resignation Date', type: 'date' },
      { key: 'last_working_day', label: 'Last Working Day', type: 'date' },
      { key: 'reason', label: 'Reason', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['initiated', 'in_progress', 'completed'] },
      { key: 'clearance_it', label: 'IT Clearance Done', type: 'checkbox' },
      { key: 'clearance_finance', label: 'Finance Clearance Done', type: 'checkbox' },
      { key: 'clearance_assets', label: 'Asset Clearance Done', type: 'checkbox' },
      { key: 'exit_interview_notes', label: 'Exit Interview Notes', type: 'textarea' },
    ],
  },
];

export const HRM_CUSTOM_PAGES = [
  { key: 'hr-dashboard', num: 15, label: 'HR Dashboard', path: '/hrm/dashboard' },
  { key: 'payroll', num: 8, label: 'Payroll', path: '/hrm/payroll-page' },
  { key: 'employee-documents', num: 12, label: 'Employee Documents', path: '/hrm/documents-page' },
];
